language: node_js
node_js:
- '6.11.2'

branches:
  only:
    develop

install:
  - npm install -g node-sass

before_script:
  - git checkout develop

script:
  - npm run sass

after_success:
  - openssl aes-256-cbc -K $encrypted_d256d7c8628c_key -iv $encrypted_d256d7c8628c_iv -in sample_key.enc -out sample_key -d > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "osaka@wordcamp.org"
  - git config --global user.name "Travis CI"
  - git checkout master
  - git merge --no-ff develop
  - git push origin master
